#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/tamizhanban/Documents/SRIP/devel_isolated/python_orocos_kdl:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH='/home/tamizhanban/Documents/SRIP/devel_isolated/orocos_kdl/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_teleop/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_controller/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_control_gui/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/my_moveit_codes/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_msgs/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_moveit_config/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_moveit/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_libs/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_hw/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_gazebo/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_description/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_controllers/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/om_service_call_examples/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/moveit_tutorials/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/mobile_robot/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/learning_tf2/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/kdl_parser_py/lib:/home/tamizhanban/Documents/SRIP/devel_isolated/kdl_parser/lib:/home/tamizhanban/Documents/SRIP/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu'
export PATH='/opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/tamizhanban/Documents/SRIP/devel_isolated/orocos_kdl/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_teleop/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_controller/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_control_gui/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/my_moveit_codes/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_msgs/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_moveit_config/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_moveit/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_libs/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_hw/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_gazebo/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_description/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_controllers/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/om_service_call_examples/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/moveit_tutorials/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/mobile_robot/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/learning_tf2/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/kdl_parser_py/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel_isolated/kdl_parser/lib/pkgconfig:/home/tamizhanban/Documents/SRIP/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/tamizhanban/Documents/SRIP/devel_isolated/open_manipulator_msgs/lib/python3/dist-packages:/home/tamizhanban/Documents/SRIP/devel_isolated/kdl_parser_py/lib/python3/dist-packages:/home/tamizhanban/Documents/SRIP/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/tamizhanban/Documents/SRIP/devel_isolated/python_orocos_kdl/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/tamizhanban/Documents/SRIP/src/orocos_kinematics_dynamics/python_orocos_kdl:/home/tamizhanban/Documents/SRIP/devel_isolated/orocos_kdl/share:$ROS_PACKAGE_PATH"